version: '3'
services:
  aprsd:
    build:
      context: .
    image: polaric-server
    entrypoint: /usr/bin/polaric-aprsd-start
    expose:
      - "8081"
    ports:
      - "8081:8081"
    volumes:
      - "./config/polaric-aprsd/passwd:/etc/polaric-aprsd/passwd"
      - "./config/polaric-aprsd/server.ini:/etc/polaric-aprsd/server.ini"
      - "./config/polaric-aprsd/symbols:/etc/polaric-aprsd/symbols"
      - "./config/polaric-aprsd/trailcolours:/etc/polaric-aprsd/trailcolours"
      - "./config/polaric-aprsd/view.profiles:/etc/polaric-aprsd/view.profiles"
      - "./config/polaric-aprsd/config.d:/etc/polaric-aprsd/config.d"
      - "aprsd-data:/var/lib/polaric"
  webapp2:
    build:
      context: .
    image: polaric-server
    entrypoint: apachectl -D FOREGROUND
    expose:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - "./config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "./config/polaric-webapp2:/etc/polaric-webapp2"
      - "mapcache:/var/lib/polaric/mapcache"
volumes:
  aprsd-data:
  mapcache:
